# Generated by Django 3.2.5 on 2021-08-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('male', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], null=True)),
                ('age', models.IntegerField(null=True)),
                ('weight_kg', models.FloatField(null=True)),
                ('height_cm', models.FloatField(null=True)),
                ('activity_coefficient', models.FloatField(choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (exercise 1–3 days/week)'), (1.55, 'Moderately active (exercise 3–5 days/week)'), (1.725, 'Active (exercise 6–7 days/week)'), (1.9, 'Very active (hard exercise 6–7 days/week)')], null=True)),
                ('meals_p_day', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)], default=3, null=True)),
                ('goal', models.IntegerField(choices=[(-1, 'Weight loss'), (0, 'Weight maintenance'), (1, 'Gain weight')], default=0, null=True)),
                ('bmr', models.IntegerField(editable=False, null=True)),
                ('amr', models.IntegerField(editable=False, null=True)),
                ('bmi', models.FloatField(editable=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
