# Generated by Django 3.2.5 on 2021-08-31 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeToApprove',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('kcal', models.IntegerField(null=True)),
                ('source_link', models.TextField(max_length=500, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('A challenge', 'A challenge'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('image_url', models.TextField(max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('kcal', models.IntegerField(null=True)),
                ('source_link', models.TextField(max_length=500, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('A challenge', 'A challenge'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('image_url', models.TextField(max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
